from __future__ import annotations

import argparse
import json
from pathlib import Path

from .adapter import normalize_diagnostic_input
from .contracts import (
    dump_json,
    load_json,
    validate_diagnostic_bundle,
    validate_loop_decision_bundle,
    validate_probe_request_bundle,
    validate_probe_result_bundle,
    validate_recommendation_bundle,
)
from .feedback import build_loop_decision_bundle, build_probe_request_bundle
from .heuristics import build_recommendation_bundle


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="model_selector",
        description="Heuristic model recommendation engine (diagnostic JSON in, recommendation JSON out).",
    )
    p.add_argument(
        "--diagnostic-in",
        required=True,
        help="Path to diagnostic bundle JSON (or legacy assumptions JSON).",
    )
    p.add_argument(
        "--recommendation-out",
        required=True,
        help="Path to recommendation JSON file (or directory).",
    )
    p.add_argument(
        "--normalized-diagnostic-out",
        default=None,
        help="Optional path to write normalized diagnostic_bundle.v1 JSON.",
    )
    p.add_argument(
        "--max-candidates",
        type=int,
        default=3,
        help="Maximum number of candidate architectures per dataset.",
    )
    p.add_argument(
        "--probe-result-in",
        default=None,
        help="Optional probe_result_bundle.v1 JSON from collator/HPO feedback loop.",
    )
    p.add_argument(
        "--loop-decision-out",
        default=None,
        help="Optional output path for loop_decision_bundle.v1 JSON.",
    )
    p.add_argument(
        "--probe-request-out",
        default=None,
        help="Optional output path for probe_request_bundle.v1 JSON (emitted only when action=request_probes).",
    )
    p.add_argument(
        "--loop-run-id",
        default=None,
        help="Optional stable loop run id; autogenerated if omitted.",
    )
    p.add_argument(
        "--round-index",
        type=int,
        default=1,
        help="Feedback loop round index (1-based).",
    )
    p.add_argument(
        "--max-rounds",
        type=int,
        default=3,
        help="Maximum feedback loop rounds before stop.",
    )
    p.add_argument(
        "--max-total-probes",
        type=int,
        default=12,
        help="Maximum total probes budget for loop control.",
    )
    p.add_argument(
        "--max-probes-per-dataset",
        type=int,
        default=2,
        help="Maximum probe requests per dataset per round.",
    )
    p.add_argument(
        "--min-confidence-gain",
        type=float,
        default=0.02,
        help="Minimum mean confidence gain required to keep probing when no blocked datasets remain.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    raw = load_json(args.diagnostic_in)
    normalized = normalize_diagnostic_input(raw)

    diag_errors = validate_diagnostic_bundle(normalized)
    if diag_errors:
        print("Diagnostic bundle validation failed:")
        for err in diag_errors:
            print(f"  - {err}")
        return 2

    if args.normalized_diagnostic_out:
        p = _resolve_json_output(args.normalized_diagnostic_out, default_name="diagnostic_bundle.json")
        p.write_text(json.dumps(normalized, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Normalized diagnostic bundle written to {p}")

    probe_result_bundle = None
    if args.probe_result_in:
        probe_result_bundle = load_json(args.probe_result_in)
        probe_errors = validate_probe_result_bundle(probe_result_bundle)
        if probe_errors:
            print("Probe result bundle validation failed:")
            for err in probe_errors:
                print(f"  - {err}")
            return 4

    rec = build_recommendation_bundle(normalized, max_candidates=max(1, args.max_candidates))
    rec_errors = validate_recommendation_bundle(rec)
    if rec_errors:
        print("Recommendation bundle validation failed:")
        for err in rec_errors:
            print(f"  - {err}")
        return 3

    out = dump_json(args.recommendation_out, rec)
    print(f"Recommendation bundle written to {out}")

    loop_decision = build_loop_decision_bundle(
        normalized,
        rec,
        probe_result_bundle=probe_result_bundle,
        loop_run_id=args.loop_run_id,
        round_index=max(1, args.round_index),
        max_rounds=max(1, args.max_rounds),
        max_total_probes=max(1, args.max_total_probes),
        min_confidence_gain=max(0.0, args.min_confidence_gain),
    )
    decision_errors = validate_loop_decision_bundle(loop_decision)
    if decision_errors:
        print("Loop decision bundle validation failed:")
        for err in decision_errors:
            print(f"  - {err}")
        return 5

    if args.loop_decision_out:
        path = _resolve_json_output(args.loop_decision_out, default_name="loop_decision_bundle.json")
        path.write_text(json.dumps(loop_decision, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Loop decision bundle written to {path}")

    action = str(((loop_decision.get("decision") or {}).get("action")) if isinstance(loop_decision, dict) else "")
    if args.probe_request_out and action == "request_probes":
        probe_request = build_probe_request_bundle(
            normalized,
            rec,
            probe_result_bundle=probe_result_bundle,
            loop_run_id=str(loop_decision.get("loop_run_id")),
            round_index=max(1, args.round_index),
            max_rounds=max(1, args.max_rounds),
            max_total_probes=max(1, args.max_total_probes),
            min_confidence_gain=max(0.0, args.min_confidence_gain),
            max_probes_per_dataset=max(1, args.max_probes_per_dataset),
        )
        req_errors = validate_probe_request_bundle(probe_request)
        if req_errors:
            print("Probe request bundle validation failed:")
            for err in req_errors:
                print(f"  - {err}")
            return 6
        p = _resolve_json_output(args.probe_request_out, default_name="probe_request_bundle.json")
        p.write_text(json.dumps(probe_request, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Probe request bundle written to {p}")
    elif args.probe_request_out:
        print(f"Probe request bundle not emitted (loop action={action!r}).")

    return 0


def _resolve_json_output(raw: str, *, default_name: str) -> Path:
    path = Path(raw).expanduser()
    if path.exists() and path.is_dir():
        return path / default_name
    if path.suffix.lower() != ".json":
        path.mkdir(parents=True, exist_ok=True)
        return path / default_name
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
