from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, Tuple

from .assembler import SnippetAssembler
from .codegen import assemble_file
from .config_io import dump_config, load_config
from .db import SnippetDB, build_db
from .errors import ConfigError
from .snippets import Snippet
from .templates import get_templates_for_pipeline


def _iter_pipelines(raw: Dict[str, Any]) -> Iterable[Dict[str, Any]]:
    pipes = raw.get("pipelines", [])
    if not isinstance(pipes, list):
        raise ConfigError("'pipelines' must be a list")
    for p in pipes:
        if not isinstance(p, dict):
            continue
        if not isinstance(p.get("name"), str) or not isinstance(p.get("kind"), str):
            continue
        yield p


class ProjectGenerator:
    """Generate pipeline folders from a project config.

    This is intentionally small and boring: load config -> plan files -> assemble snippets.
    """

    def __init__(self, *, txt_store: Path, db_path: Path) -> None:
        self.txt_store = Path(txt_store)
        self.db_path = Path(db_path)

    def _ensure_db(self) -> SnippetDB:
        # Auto-refresh the registry if snippets changed.
        needs_rebuild = not self.db_path.exists()
        if not needs_rebuild and self.txt_store.exists():
            newest = max(
                (p.stat().st_mtime for p in self.txt_store.rglob("*.txt")),
                default=0.0,
            )
            needs_rebuild = newest > self.db_path.stat().st_mtime

        if needs_rebuild:
            build_db(self.txt_store, self.db_path)
        return SnippetDB(db_path=self.db_path, txt_root=self.txt_store)

    def generate(
        self,
        *,
        project_file: str | Path,
        out_dir: str | Path,
        force: bool = False,
        pipeline_config_format: str = "toml",
    ) -> Tuple[Path, int]:
        """Generate pipeline folders.

        Args:
            project_file: Project config (.toml or .yaml/.yml)
            out_dir: Output directory
            force: If True, overwrite existing pipeline directories
            pipeline_config_format: "toml" (recommended) or "yaml"

        Returns:
            (out_dir, num_pipelines_generated)
        """
        project_file = Path(project_file)
        out_dir = Path(out_dir)

        raw = load_config(project_file)
        out_dir.mkdir(parents=True, exist_ok=True)

        db = self._ensure_db()

        count = 0
        for p in _iter_pipelines(raw):
            name = str(p["name"])
            kind = str(p["kind"]).lower()
            enabled = bool(p.get("enabled", True))
            if not enabled:
                continue

            file_templates = get_templates_for_pipeline(kind, p)
            if not file_templates:
                raise ConfigError(f"No templates registered for pipeline kind '{kind}'.")

            pipe_dir = out_dir / name
            if pipe_dir.exists():
                if not force:
                    raise ConfigError(
                        f"Output already exists for pipeline '{name}': {pipe_dir}. Use --force to overwrite."
                    )
                shutil.rmtree(pipe_dir)

            # Make folders
            (pipe_dir / "src").mkdir(parents=True, exist_ok=True)
            (pipe_dir / "config").mkdir(parents=True, exist_ok=True)

            # Write pipeline config in a sane format.
            if pipeline_config_format not in {"toml", "yaml"}:
                raise ConfigError("pipeline_config_format must be 'toml' or 'yaml'")
            cfg_name = f"pipeline.{pipeline_config_format}"
            (pipe_dir / "config" / cfg_name).write_text(
                dump_config(p, fmt=pipeline_config_format),
                encoding="utf-8",
            )

            # Generated python files
            for ft in file_templates:
                out_path = pipe_dir / ft.out_relpath
                module_doc = f"Generated by mmtool prototype v2 for pipeline '{name}'."

                if ft.out_relpath == "src/criterion.py":
                    _write_criterion(
                        db=db,
                        pipe_cfg=p,
                        out_path=out_path,
                        module_docstring=module_doc,
                    )
                else:
                    assemble_file(
                        db=db,
                        snippet_keys=ft.snippet_keys,
                        out_path=out_path,
                        module_docstring=module_doc,
                    )

            # Small package init
            (pipe_dir / "src" / "__init__.py").write_text(
                """# Generated pipeline package
from .model import *  # noqa
from .criterion import *  # noqa
from .config import *  # noqa
from .data import *  # noqa
""",
                encoding="utf-8",
            )

            (pipe_dir / "README.md").write_text(
                _pipeline_readme(name=name, cfg_name=cfg_name),
                encoding="utf-8",
            )

            count += 1

        return out_dir, count


def generate(
    *,
    project_file: str | Path,
    out_dir: str | Path,
    txt_store: str | Path,
    db_path: str | Path,
    force: bool = False,
    pipeline_config_format: str = "toml",
) -> Tuple[Path, int]:
    """Backwards-friendly wrapper for the CLI."""
    gen = ProjectGenerator(txt_store=Path(txt_store), db_path=Path(db_path))
    return gen.generate(
        project_file=Path(project_file),
        out_dir=Path(out_dir),
        force=force,
        pipeline_config_format=pipeline_config_format,
    )


def _pipeline_readme(*, name: str, cfg_name: str) -> str:
    return f"""# {name}

This folder was generated by the **mmtool prototype v2**.

## What you get
- `config/{cfg_name}`: your pipeline config
- `src/model.py`: model code (architecture + forward only)
- `src/criterion.py`: loss/criterion code (separate classes)
- `src/config.py`: dataclass-based config loader
- `src/data.py`: dataset + dataloader helpers
- `src/run_demo.py`: quick smoke-test
- `src/train.py`: minimal training skeleton

## Try it
```bash
python src/run_demo.py
python src/train.py
```
"""


# Backwards-friendly name for the CLI.
generate_project = generate


# --- Criterion assembly helpers ---

LOSS_KEY_MAP = {
    "cross_entropy": "ce",
    "ce": "ce",
    "bce_with_logits": "bce",
    "bce": "bce",
    "mse": "mse",
    "l2": "mse",
}

LOSS_CLASS = {
    "ce": "CrossEntropyCriterion",
    "bce": "BCEWithLogitsCriterion",
    "mse": "MSECriterion",
}


def _canonical_loss(name: str) -> str:
    key = LOSS_KEY_MAP.get(name.lower())
    if not key:
        raise ConfigError(f"Unsupported criterion kind '{name}'.")
    return key


def _build_factory_single(loss_key: str) -> str:
    cls = LOSS_CLASS[loss_key]
    alias_map = {k: v for k, v in LOSS_KEY_MAP.items() if v == loss_key}
    lines = [
        "def make_single_task_criterion(kind: str, *, label_smoothing: float = 0.0, pos_weight: Optional[float] = None) -> Criterion:",
        f"    _canon = {alias_map!r}.get(kind.lower())",
        f"    if _canon != '{loss_key}':",
        "        raise ValueError(f\"Unsupported criterion kind '{kind}' for this pipeline.\")",
    ]
    if loss_key == "ce":
        lines.append(f"    return {cls}(label_smoothing=label_smoothing)")
    elif loss_key == "bce":
        lines.append(f"    return {cls}(pos_weight=pos_weight)")
    else:
        lines.append(f"    return {cls}()")
    return "\n".join(lines) + "\n"


def _build_factory_mtl(loss_keys: set[str]) -> str:
    alias_map = {k: v for k, v in LOSS_KEY_MAP.items() if v in loss_keys}
    lines = [
        "def make_single_task_criterion(kind: str, *, label_smoothing: float = 0.0, pos_weight: Optional[float] = None) -> Criterion:",
        f"    _canon = {alias_map!r}.get(kind.lower())",
    ]
    for k in sorted(loss_keys):
        cls = LOSS_CLASS[k]
        lines.append(f"    if _canon == '{k}':")
        if k == "ce":
            lines.append(f"        return {cls}(label_smoothing=label_smoothing)")
        elif k == "bce":
            lines.append(f"        return {cls}(pos_weight=pos_weight)")
        else:
            lines.append(f"        return {cls}()")
    allowed = ",".join(sorted(loss_keys))
    lines.append(
        f"    raise ValueError(f\"Unsupported criterion kind '{{kind}}'; allowed: {allowed}\")"
    )
    return "\n".join(lines) + "\n"


def _criterion_snippets(db: SnippetDB, pipe_cfg: dict) -> list[Snippet]:
    def snip(name: str) -> Snippet:
        return Snippet(name=name, code=db.get_code(name))

    common = [
        snip("common.future_annotations"),
        snip("common.imports_torch"),
        snip("criteria.base"),
    ]

    kind = pipe_cfg["kind"].lower()
    crit_cfg = pipe_cfg.get("criterion", {}) or {}

    if kind in {"cnn", "mlp"}:
        loss_key = _canonical_loss(str(crit_cfg.get("kind", "")))
        class_snip = snip(f"criteria.{loss_key}")
        factory = Snippet(name="criteria.factory", code=_build_factory_single(loss_key))
        return common + [class_snip, factory]

    if kind == "mtl":
        task_losses = crit_cfg.get("task_losses", {})
        if not isinstance(task_losses, dict) or not task_losses:
            raise ConfigError(
                f"[{pipe_cfg.get('name')}] MTL pipelines need non-empty criterion.task_losses"
            )
        loss_keys = {_canonical_loss(k) for k in task_losses.values()}
        class_snips = [snip(f"criteria.{k}") for k in sorted(loss_keys)]
        factory = Snippet(name="criteria.factory", code=_build_factory_mtl(loss_keys))
        return common + class_snips + [factory, snip("criteria.mtl_weighted")]

    raise ConfigError(f"Unknown pipeline kind: {kind}")


def _write_criterion(
    *, db: SnippetDB, pipe_cfg: dict, out_path: Path, module_docstring: str
) -> None:
    snippets = _criterion_snippets(db, pipe_cfg)
    assembler = SnippetAssembler(snippets, module_docstring=module_docstring)
    assembler.write(out_path)
